### ISSUE TITLE
关于D1S time CSR寄存器的访问

### ISSUE THREAD

**Issue by XHTimmo** [YuzukiHD/SyterKit#115]
大佬好！
本人在开发D1S裸机程序的时候，参考您提供的框架代码进行部分功能的移植。在需要获取系统时钟的部分，即使用get_arch_time()函数时，板卡会崩溃重启，貌似是对time寄存器访问的时候出现了问题，请问在访问该寄存器之前需要有需要特殊操作的吗？
谢谢

**Comment by YuzukiTsuru** [comment]
没有`get_arch_time`只有`get_arch_counter`

**Comment by XHTimmo** [comment]
不好意思，打错名字了【qwq】，我意思就是这个函数【期待】

**Comment by YuzukiTsuru** [comment]
测试未复现相关问题

**Comment by XHTimmo** [comment]
好的，谢谢佬
