### ISSUE TITLE
[board]: how burn the T113i image to TF-card

### ISSUE THREAD

**Issue by ooops-t** [YuzukiHD/SyterKit#123]
1. build the t113i image
`cmake -DCMAKE_BOARD_FILE=100ask-t113i.cmake -Bbuild -H.`
2. create the sd card MBR partition
```
Welcome to fdisk (util-linux 2.38.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): p
Disk /dev/sdb: 14.84 GiB, 15931539456 bytes, 31116288 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x536d07fa

Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
```
3. burn the image to sd card
`sudo dd if=build/board/100ask-t113i/hello_world/helloworld_bin_card.bin of=/dev/sdb bs=1024 seek=8 conv=notrunc,fdatasync status=progress`

**But can't get boot message on the terminal. Please help me!**

**Comment by ooops-t** [comment]
Sorry i got it. I can control the gpio, but the serial no message print.

**Comment by YuzukiTsuru** [comment]
Check your board which uart is using with which pins, the default is uart0 in PB8,PB9 

and modify: 

sunxi_serial_t uart_dbg = {
        .base = SUNXI_UART0_BASE,
        .id = 0,
        .gpio_tx = {GPIO_PIN(GPIO_PORTB, 8), GPIO_PERIPH_MUX6},
        .gpio_rx = {GPIO_PIN(GPIO_PORTB, 9), GPIO_PERIPH_MUX6},
};

**Comment by ooops-t** [comment]
I got it. Thanks!!!
