### ISSUE TITLE
compile error t57

### ISSUE THREAD

**Issue by arm-sbc** [YuzukiHD/SyterKit#126]
[ 86%] Linking C executable extlinux_boot_bin
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: extlinux_boot_bin section `.text' will not fit in region `ram_a2'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: region `ram_a2' overflowed by 20624 bytes
collect2: error: ld returned 1 exit status
make[2]: *** [board/avaota-a1/extlinux_boot/CMakeFiles/extlinux_boot_bin.dir/build.make:183: board/avaota-a1/extlinux_boot/extlinux_boot_bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:1039: board/avaota-a1/extlinux_boot/CMakeFiles/extlinux_boot_bin.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by arm-sbc** [comment]
ubuntu 22.04 version

**Comment by YuzukiTsuru** [comment]
Tested with Github CI，Build passed
