### ISSUE TITLE
maybe wrong offset address for TWI ?

### ISSUE THREAD

**Issue by mathl79** [YuzukiHD/SyterKit#148]
**Describe the bug**
I am not 100% sure if it is a bug, but i stumbled over a mismatch between the T113-s3 manual and the register offset in the file  [reg-ncat.h](https://github.com/YuzukiHD/SyterKit/blob/main/include/drivers/chips/sun8iw20/reg-ncat.h)

Instead of the value 0x019C in the file, the register TWI_BGR_REG should have an offset of 0x091C according the manual.

**To Reproduce**
nothing to reproduce

**Expected behavior**

**Screenshots**
screenshot from the manual.
![grafik](https://github.com/user-attachments/assets/ce5d03d5-9608-4bda-9d6b-1a5697e0eac4)

**Desktop (please complete the following information):**
 - SoC:  T113-s3   maybe others too ?!?

**Additional context**
i am just starting to work with this platform, so please be patient if i got this wrong.

**Comment by SamulKyull** [comment]
https://github.com/YuzukiHD/SyterKit/blob/72d608f77531d6db60e2a7b5dd32b0d9efda2b89/include/drivers/chips/sun8iw20/reg-ccu.h#L71

This `SUNXI_RTWI_BRG_REG` is CPUs RTWI, Because this chip does not have CPUs, it will not use the definition here.
```
#define SUNXI_RTWI_BRG_REG (SUNXI_RPRCM_BASE + 0x019c)
```
