### ISSUE TITLE
SyterKit是否适合用来给其他SoC做启动加速，例如君正X2000

### ISSUE THREAD

**Issue by johnzchgrd** [YuzukiHD/SyterKit#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YuzukiTsuru** [comment]
SyterKit由于运行在SRAM，所以设计的时候驱动架构抽象层较为简易，不方便扩展其他平台。甚至AW的老平台都不方便支持

**Comment by johnzchgrd** [comment]
很高兴收到你的来邮件，无法立即回复你的邮件。我将尽快给你回复。若有急事请联系我的经纪人：
    
        占慧颖
    
    
        
            <
        
    
    
        ***@***.***
    
    
        >
