### ISSUE TITLE
Where can find Tina Linux code with GPU enabled for R818 ?

### ISSUE THREAD

**Issue by rqbh** [YuzukiHD/SyterKit#55]
Where can find Tina Linux code with GPU enabled for R818 match this bootloader?

**Comment by YuzukiTsuru** [comment]
Linux KM DRIVER: [GE8300-GPU-LINUX.tar.gz](https://github.com/YuzukiHD/SyterKit/files/14821786/GE8300-GPU-LINUX.tar.gz)
Linux UM DRIVER: [GE8300-GPU-UM.tar.gz](https://github.com/YuzukiHD/SyterKit/files/14821799/GE8300-GPU-UM.tar.gz)
