### ISSUE TITLE
d1h中的SPI_CCR寄存器从何而来？

### ISSUE THREAD

**Issue by Emin017** [YuzukiHD/SyterKit#76]
SPI_CCR在[代码](https://github.com/YuzukiHD/SyterKit/blob/d1f10cce48dbad273e7167694ce6c7a6c0ec52fa/src/drivers/sys-spi.c#L28)中定义的地址为
```c
enum {
    SPI_GCR = 0x04,
    SPI_TCR = 0x08,
    SPI_IER = 0x10,
    SPI_ISR = 0x14,
    SPI_FCR = 0x18,
    SPI_FSR = 0x1c,
    SPI_WCR = 0x20,
    SPI_CCR = 0x24, // 这个寄存器
    SPI_DLY = 0x28,
    SPI_MBC = 0x30,
    SPI_MTC = 0x34,
    SPI_BCC = 0x38,
    SPI_TXD = 0x200,
    SPI_RXD = 0x300,
};
```
但是我在D1h的手册中找不到SPI_CCR这个寄存器
![图片](https://github.com/YuzukiHD/SyterKit/assets/99674037/c3b93d0e-0652-4fe1-a246-4e4d4e5f758c)
不过在使用SPI的过程中，我发现这个寄存器似乎确实能实现分频的功能（注释掉了某行向这个地址写数据的代码后`write32(spi->base + SPI_CCR, reg);`，时钟频率似乎确实发生了变化），想问一下是如何得知这个地址上存在寄存器的呢？

**Comment by YuzukiTsuru** [comment]
![image](https://github.com/YuzukiHD/SyterKit/assets/12003087/cd57a87d-a3b7-4381-a26d-53013cacaf0b)

这个寄存器是控制SPI时钟的，在新版IP中已经不推荐这样使用，但是这里为了方便还是这样设置

**Comment by YuzukiTsuru** [comment]
新版本需要控制父时钟并设置分频，通过CCU控制输入时钟而不是使用SPI硬件，这样可以获得更灵活的频率，但是需要实现完整的clk框架，目前SyterKit使用的是简易框架没有实现

**Comment by Emin017** [comment]
OK，感谢大佬（最后想问一下有旧版本的文档吗

**Comment by YuzukiTsuru** [comment]
这不是老版本手册，这是H616的手册，SPI驱动是在H616上实现的

**Comment by XHTimmo** [comment]
我可以理解为两块芯片使用的是同一个SPI控制器，所以D1S的配置和使用的方式也可以参照H616嘛

**Comment by YuzukiTsuru** [comment]
不是一个控制器，有部分升级，只是在boot阶段需求较少这样用没问题

**Comment by XHTimmo** [comment]
那框架中sys-spi只适用于boot。如果要用来驱动外设的话，驱动代码是不完整的嘛。

**Comment by YuzukiTsuru** [comment]
是的，使用SPI_CCR的时钟分频非常粗糙，只有几个固定频点可以用

**Comment by XHTimmo** [comment]
好的，那我再自己RTFM研究一下，如果后续还是不能驱动ST7789再来请教大佬

**Comment by XHTimmo** [comment]
大佬好！
本人在开发D1S裸机程序的时候，参考您提供的框架代码进行部分功能的移植。在需要获取系统时钟的部分，即使用get_arch_time()函数时，板卡会崩溃重启，貌似是对time寄存器访问的时候出现了问题，请问在访问该寄存器之前需要有需要特殊操作的吗？
谢谢
